server:
  port: 8802
  servlet:
    context-path: /cheeseKing
spring:
  datasource:
    password: Dragon123654789
    url: jdbc:mysql://localhost:3306/javawebprojectcheeseking?user=root&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC